// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"SRCrazy_Core","status":true,"description":"v1.2 Required for most SRCrazy scripts. Provides some additional functions to standard classes.\n<SRCrazy_Core>","parameters":{"Cache Event Commands":"true"}},
{"name":"SRCrazy_EventIndicators","status":true,"description":"v0.3.2 Displays indicators above events\n<SRCrazy_EventIndicators>","parameters":{"Disabled At Start":"false","-- Icon Settings --":"","Icon Filename":"IconSet","Icon File Path":"system","Icon Width":"32","Icon Height":"32","-- Display Settings --":"","Y Offset":"-38","Opacity":"255","Layer Order":"5","Scale":"1","Hue":"0","-- Tween Settings --":"","Tween Position X":"false 0 0 1","Tween Position Y":"false 0 0 1","Tween Scale X":"false 0 0 1","Tween Scale Y":"false 0 0 1","Tween Opacity":"false 0 0 1","Tween Layer Order":"false 0 0 1","Tween Hue":"false 0 0 1"}}
];
